/** @type {import('tailwindcss').Config} */
const colorVar = (name) => `rgb(var(${name}) / <alpha-value>)`

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        sage: {
          50: colorVar('--sage-gray-50'),
          100: colorVar('--sage-gray-100'),
          200: colorVar('--sage-gray-200'),
          300: colorVar('--sage-gray-300'),
          400: colorVar('--sage-gray-400'),
          500: colorVar('--sage-gray-500'),
          600: colorVar('--sage-gray-600'),
          700: colorVar('--sage-gray-700'),
          800: colorVar('--sage-gray-800'),
          900: colorVar('--sage-gray-900'),
          black: colorVar('--sage-black'),
          charcoal: colorVar('--sage-gray-800'),
          stone: colorVar('--sage-gray-700'),
          slate: colorVar('--sage-gray-500'),
          mist: colorVar('--sage-gray-400'),
          whisper: colorVar('--sage-gray-300'),
          pearl: colorVar('--sage-gray-100'),
          white: colorVar('--sage-white'),
          gray: {
            50: colorVar('--sage-gray-50'),
            100: colorVar('--sage-gray-100'),
            200: colorVar('--sage-gray-200'),
            300: colorVar('--sage-gray-300'),
            400: colorVar('--sage-gray-400'),
            500: colorVar('--sage-gray-500'),
            600: colorVar('--sage-gray-600'),
            700: colorVar('--sage-gray-700'),
            800: colorVar('--sage-gray-800'),
            900: colorVar('--sage-gray-900'),
          },
        },
        gold: {
          50: colorVar('--sage-gold-light'),
          100: colorVar('--sage-gold-light'),
          200: colorVar('--sage-gold-light'),
          300: colorVar('--sage-gold-light'),
          400: colorVar('--sage-gold'),
          500: colorVar('--sage-gold'),
          600: colorVar('--sage-gold'),
          700: colorVar('--sage-gold-dark'),
          800: colorVar('--sage-gold-dark'),
          900: colorVar('--sage-gold-dark'),
          dark: colorVar('--sage-gold-dark'),
          DEFAULT: colorVar('--sage-gold'),
          light: colorVar('--sage-gold-light'),
          pale: colorVar('--sage-gold-light'),
        },
        'sage-gold': colorVar('--sage-gold'),
        'sage-gold-dark': colorVar('--sage-gold-dark'),
        'sage-gray-50': colorVar('--sage-gray-50'),
        'sage-gray-100': colorVar('--sage-gray-100'),
        'sage-gray-200': colorVar('--sage-gray-200'),
        'sage-gray-300': colorVar('--sage-gray-300'),
        'sage-gray-500': colorVar('--sage-gray-500'),
        'sage-gray-600': colorVar('--sage-gray-600'),
        'sage-gray-700': colorVar('--sage-gray-700'),
        'sage-black': colorVar('--sage-black'),
        'sage-white': colorVar('--sage-white'),
        destructive: colorVar('--destructive'),
        card: colorVar('--card'),
        background: colorVar('--background'),
        foreground: colorVar('--foreground'),
        primary: colorVar('--primary'),
        secondary: colorVar('--secondary'),
        accent: colorVar('--accent'),
        muted: colorVar('--muted'),
        border: colorVar('--border'),
        input: colorVar('--input'),
        ring: colorVar('--ring'),
      },
      textColor: {
        foreground: colorVar('--foreground'),
        'primary-foreground': colorVar('--primary-foreground'),
        'secondary-foreground': colorVar('--secondary-foreground'),
        'accent-foreground': colorVar('--accent-foreground'),
        'muted-foreground': colorVar('--muted-foreground'),
        'destructive-foreground': colorVar('--destructive-foreground'),
        'card-foreground': colorVar('--card-foreground'),
        'input-foreground': colorVar('--input-foreground'),
      },
      backgroundColor: {
        background: colorVar('--background'),
        foreground: colorVar('--foreground'),
        primary: colorVar('--primary'),
        secondary: colorVar('--secondary'),
        accent: colorVar('--accent'),
        muted: colorVar('--muted'),
        card: colorVar('--card'),
        destructive: colorVar('--destructive'),
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Playfair Display', 'Georgia', 'serif'],
      },
      animation: {
        'shimmer': 'shimmer 2s infinite',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'spin': 'spin 1s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      boxShadow: {
        'elegant': '0 2px 8px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'elegant-lg': '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
        'gold': '0 2px 8px rgba(201, 169, 110, 0.15), 0 1px 2px rgba(201, 169, 110, 0.1)',
        'gold-lg': '0 4px 16px rgba(201, 169, 110, 0.2), 0 2px 6px rgba(201, 169, 110, 0.15)',
      },
    },
  },
  plugins: [],
}
